# -*- coding: utf-8 -*-
"""R134aLookupTable.ipynb
​
Automatically generated by Colaboratory.
​
Original file is located at
    https://colab.research.google.com/drive/1U540uSqHOxuvcEsJuiN_EbPey5jxyjN1
"""
# from CoolProp.CoolProp import PropsSI
# import sys

# myfile = open('F:\\kianwee_work\\spyder_workspace\\heat_pump_controls\\read_heat_pump\\refrigerant_temp.txt', 'w')
# myfile.write("static float R134A_SAT[]={")
# for x in range (70000, 4000000, 1000):
#     # print(PropsSI('T','P',x,'Q',0,'R134A'))
#     #x = 70000
#     temp = PropsSI('T','P',x,'Q',0,'R134A') - 273.15
#     print(temp)
#     myfile.write(str(format((PropsSI('T','P',x,'Q',0,'R134A') - 273.15), '.2f')))
#     myfile.write(",")

# myfile.write("0,0};")
# myfile.close()
x =  'v' + str(125)
b = str.encode(x)

print(type(b))